worker_processes auto;
worker_rlimit_nofile 8192;

events {
    worker_connections 1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    access_log /var/log/nginx/access.log;
    error_log  /var/log/nginx/error.log;

    sendfile on;
    tcp_nopush on;
    tcp_nodelay on;
    keepalive_timeout 65;
    types_hash_max_size 2048;

    server {
        listen 80;
        server_name localhost;

        root /var/www/html/public;
        index index.php index.html index.htm;

        # Обслуживание статических файлов
        location / {
            try_files $uri $uri/ /index.php$is_args$args;
        }

        # Обработка PHP-запросов для currency-service
        location ~ ^/currency(/|$) {
            try_files $uri /currency/index.php$is_args$args;
            fastcgi_pass currency-service:9000;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            include fastcgi_params;
        }

        # Обработка PHP-запросов для report-generation-service
        location ~ ^/report(/|$) {
            try_files $uri /report/index.php$is_args$args;
            fastcgi_pass report-generation-service:9000;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            include fastcgi_params;
        }

        # Защита от доступа к конфиденциальным файлам
        location ~* \.(ht|git|svn|env|ini|phar)$ {
            deny all;
        }

        # Обработка ошибок
        error_page 404 /404.html;
        location = /404.html {
            internal;
        }
    }
}
